### ISSUE TITLE
[Bug] Android: The color picker doesn't work

### ISSUE THREAD

**Issue by Xto-tT0** [anareaty/pretty-properties#59]
### Bug description
The colour palette does not work. The black window cannot be clicked. Everything worked fine at first, but then the problem appeared.

### Steps to reproduce
1. Open Obsidian
2. Long press on the property
3. "Select a colour"
4. "Your colour"

Or do the same thing, but through the settings

### Expected behaviour
You should be able to select a colour from your palette. 

### Actual behaviour
A black window with no option to click anywhere. 

### General information
Android 13
Obsidian 1.10.6
Pretty Properties 1.9.9

https://youtube.com/shorts/r2-Zez0wdCI

**Comment by anareaty** [comment]
It works normally for me. Did you try ot with other plugins / themes disabled?

**Comment by Xto-tT0** [comment]
Interestingly, after testing, it turned out that the "Always Color Text" plugin was to blame.
After disabling it, the problem disappeared.

**Comment by anareaty** [comment]
It seems that this other plugin changes the style of the color input. I'm going to add some style changes in the next release that will hopufully fix this issue.

**Comment by anareaty** [comment]
I added some style changes it the new release, so the plugins should now work well together. Please, check if it works well on your side.

**Comment by Xto-tT0** [comment]
Sorry for the late reply. I updated both plugins and the problem persists in my case. Perhaps I should send a sample of the storage to help solve the problem?

**Comment by anareaty** [comment]
Yeah, it would be better. Maybe some other plugins and themes also affect it.

**Comment by Xto-tT0** [comment]
Again, I apologize for the long delay. After the updates (presumably with the new android version), the issue has been resolved. 

The issue has been closed, thanks!
